spring.application.name=hotel-reservas-app

# Puedes sobreescribir con variables de entorno: DB_URL, DB_USER, DB_PASSWORD
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hotel_reservas_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:aNdresch13@.}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
